language: node_js
node_js:
  - "8"

sudo: required


addons:
  firefox: latest
  chrome: stable

os:
  - linux

install:
  - npm i -g npm@^5.3.0 && npm --version
  - (cd angular && npm install)

# before_script:
#   - export DISPLAY=:99.0
#   - sh -e /etc/init.d/xvfb start

# e2e tests are not currently working under Travis; running only unit
# tests for now
# 
# script:
#   - scripts/testall.travis --unitonly
script:
  #  - scripts/testall --cdv 2.44
   - scripts/testall
   - scripts/makedist

# after_script:
#   - pkill gulp

cache:
  directories: node_modules

